### ISSUE TITLE
プロフィールを編集したい

### ISSUE THREAD

**Issue by yukari-h602** [yukari-h602/oshi-katsu#20]
ruby "3.0.2"``Rails 7.0.6 を使用しています。
・質問内容・実現したいこと
プロフィールの編集をしたいです。

- 現状発生している問題・エラーメッセージ
編集画面より`更新`ボタンを押すと`ArgumentError`が発生しました。
引数が合わないと言われているのはわかるのですが、コードを確認しても、どの引数が違うのか発見できず、行き詰まっています。
アドバイス等いただけると嬉しいです。
<img width="1074" alt="スクリーンショット 2023-08-15 15 15 51" src="https://github.com/yukari-h602/oshi-katsu/assets/117580975/5c880819-0b98-4364-a62b-1697061b393e">

```
Started PATCH "/profile" for ::1 at 2023-08-15 14:42:38 +0900
Processing by ProfilesController#update as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"ws@sample.com", "name"=>"yui", "hobby"=>"test", "avatar"=>#<ActionDispatch::Http::UploadedFile:0x00000001229bd700 @tempfile=#<Tempfile:/var/folders/xm/ymnv362s0y78r9w1mft38wsm0000gn/T/RackMultipart20230815-15849-clz7lu.jpeg>, @content_type="image/jpeg", @original_filename="IMG_1093.jpeg", @headers="Content-Disposition: form-data; name=\"user[avatar]\"; filename=\"IMG_1093.jpeg\"\r\nContent-Type: image/jpeg\r\n">, "avatar_cache"=>""}, "commit"=>"更新する"}
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/profiles_controller.rb:20:in `set_user'
Completed 500 Internal Server Error in 13ms (ActiveRecord: 1.3ms | Allocations: 3433)


  
ArgumentError (wrong number of arguments (given 2, expected 1)):
  
app/controllers/profiles_controller.rb:9:in `update'
```
- どの処理までうまく動いているのか
プロフィール詳細画面から編集画面に遷移し、編集内容を記載した後、更新ボタンを押したところでエラーになっています。
- 該当のソースコード
`profiles_controller.rb`
```
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:email, :name, :hobby, :avatar, :avatar_cache)
  end
end
```
`profiles/show.html.erb`
```
<div class="wrapper">
  <div class="container pt-3">
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <h1 class="float-left mb-5"><%= t('.title') %></h1>
        <%= link_to t('defaults.edit'), edit_profile_path, class: 'btn btn-warning' %>
        <table class="table">
          <tr>
            <th scope="row"><%= User.human_attribute_name(:email) %></th>
            <td><%= current_user.email %></td>
          </tr>
          <tr>
            <th scope="row"><%= User.human_attribute_name(:name) %></th>
            <td><%= current_user.name %></td>
          </tr>
          <tr>
            <th scope="row"><%= User.human_attribute_name(:hobby) %></th>
            <td><%= current_user.hobby %></td>
          </tr>
          <tr>
            <th scope="row"><%= User.human_attribute_name(:avatar) %></th>
            <td><%= image_tag current_user.avatar.url, class: 'rounded-circle', size: '50x50' %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>
```
`profiles/edit.html.erb`
```
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <h1><%= t('.title') %></h1>
        <%= form_with model: @user, url: profile_path, local: true do |f| %>
          <%= render "shared/error_messages", object: f.object %>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control mb-3" %>
          </div>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control mb-3" %>
          </div>
          <div class="form-group">
            <%= f.label :hobby %>
            <%= f.text_area :hobby, class: "form-control mb-3" %>
          </div>
          <div class="form-group">
            <%= f.label :avatar %>
            <%= f.file_field :avatar, class: "form-control", accept: 'image/*', onchange: 'previewImage(preview)' %>
            <%= f.hidden_field :avatar_cache %>
            <div class='mt-3 mb-3'>
              <%= image_tag @user.avatar.url, id: 'preview', size: '100x100', class: 'rounded-circle' %>
            </div>
          </div>
          <%= f.submit  class: "btn btn-primary mb-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
```
`user.rb`
```
class User < ApplicationRecord
  authenticates_with_sorcery!

	mount_uploader :avatar, AvatarUploader

	has_many :boards, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :bookmarks, dependent: :destroy
	has_many :bookmark_boards, through: :bookmarks, source: :board

	validates :password, length: { minimum: 3}, if: -> { new_record? || chaneges[:crypted_password] }
	validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
	validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
	
	validates :email, uniqueness: true, presence: true
	validates :name, presence: true, length: { maximum: 255 }
(略)
```
`routes.rb`
```
Rails.application.routes.draw do
  root 'static_pages#top'

	get 'terms_of_service', to: 'static_pages#terms_of_service'
	get 'privacy_policy', to: 'static_pages#privacy_policy'

	get 'login', to: 'user_sessions#new'
	post 'login', to: 'user_sessions#create'
	delete 'logout', to: 'user_sessions#destroy'
	
	resources :users, only: %i[new create]
	resources :boards do
		resources :comments, only: %i[create], shallow: true
		collection do
			get :bookmarks
		end
	end
	resources :bookmarks, only: %i[create destroy]

	resource :profile, only: %i[show edit update]
end
```
- エラーから考えられる原因
引数があっていない。
- 試したこと
`@user`や`user_params`には値が含まれていました。
ストロングパラメーターを確認し、`user_params`を引数として渡していることは確認しています。
```
>> @user
=> #<User id: 2, email: "ws@sample.com", crypted_password: "$2a$10$YAwUY7HpfTfan5helbsTmO9.HF90lBUYLqLMdNvQrXd...", salt: "bpdhATHpUoRH5D6fCyL1", name: "yui", created_at: "2023-08-08 18:32:56.372035000 +0900", updated_at: "2023-08-08 18:32:56.372035000 +0900", avatar: nil, hobby: "test">
>> user_params
=> #<ActionController::Parameters {"email"=>"ws@sample.com", "name"=>"yui", "hobby"=>"test", "avatar"=>#<ActionDispatch::Http::UploadedFile:0x00000001229bd700 @tempfile=#<Tempfile:/var/folders/xm/ymnv362s0y78r9w1mft38wsm0000gn/T/RackMultipart20230815-15849-clz7lu.jpeg>, @content_type="image/jpeg", @original_filename="IMG_1093.jpeg", @headers="Content-Disposition: form-data; name=\"user[avatar]\"; filename=\"IMG_1093.jpeg\"\r\nContent-Type: image/jpeg\r\n">, "avatar_cache"=>""} permitted: true>
>> @user.update
ArgumentError: wrong number of arguments (given 0, expected 1)
	from /Users/hirashimayukari/workspace/runteq/oshi-katsu/app/controllers/profiles_controller.rb:9:in `update'
```
https://qiita.com/riyontech/items/aa25b1ee3144dca5c72b

**Comment by kenchasonakai** [comment]
user_paramsから一度avatarとavatar_cacheを外して、ユーザー情報が更新されるか確認してみてください

保存できたら画像周りの設定がうまくいってない
エラーが変わらなければまた別要因かなと推測できると思います

**Comment by yukari-h602** [comment]
コメントありがとうございます。
>user_paramsから一度avatarとavatar_cacheを外して、ユーザー情報が更新されるか確認してみてください

外してみたところ、今度は`NameError`が発生しました。
```
Started PATCH "/profile" for ::1 at 2023-08-15 15:52:01 +0900
Processing by ProfilesController#update as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"ws@sample.com", "name"=>"yui", "hobby"=>"test", "avatar_cache"=>""}, "commit"=>"更新する"}
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/profiles_controller.rb:20:in `set_user'
Unpermitted parameter: :avatar_cache. Context: { controller: ProfilesController, action: update, request: #<ActionDispatch::Request:0x000000011e9fd1d8>, params: {"_method"=>"patch", "authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"ws@sample.com", "name"=>"yui", "hobby"=>"test", "avatar_cache"=>""}, "commit"=>"更新する", "controller"=>"profiles", "action"=>"update"} }
Completed 500 Internal Server Error in 46ms (ActiveRecord: 0.3ms | Allocations: 7319)


  
NameError (undefined local variable or method `chaneges' for #<User id: 2, email: "ws@sample.com", crypted_password: "$2a$10$YAwUY7HpfTfan5helbsTmO9.HF90lBUYLqLMdNvQrXd...", salt: "bpdhATHpUoRH5D6fCyL1", name: "yui", created_at: "2023-08-08 18:32:56.372035000 +0900", updated_at: "2023-08-08 18:32:56.372035000 +0900", avatar: nil, hobby: "test">
Did you mean?  changes
               changed):
  
app/models/user.rb:11:in `block in <class:User>'
app/controllers/profiles_controller.rb:9:in `update'
```
<img width="1348" alt="スクリーンショット 2023-08-15 15 59 35" src="https://github.com/yukari-h602/oshi-katsu/assets/117580975/a3fdb846-c018-4291-b5ed-fd98e1b65ad9">
どうやらパスワードのバリデーションに引っかかっているようで[こちら](https://qiita.com/sa_tech0518/items/9ae355d47952d42d3c9c)の記事を参考に
`user.rb`
```
validates :password, length: { minimum: 3}, if: -> { new_record? || chaneges[:crypted_password] },on: :create
```
パスワードのバリデーションをcreate時のみに設定したところ無事に保存することができました。
なので、画像周りの設定がうまくいっていないと思うのですが、ご助言をいただけますでしょうか？

**Comment by kenchasonakai** [comment]
画像をアップロードするための設定がしてあるかを確認してみるといいかもです
Railsだとカリキュラムでも使ったCarrierWaveやActiveStorageなどを使うことが多いかと思います

**Comment by yukari-h602** [comment]
コメントありがとうございます。
>画像をアップロードするための設定がしてあるかを確認してみるといいかもです

CarrierWaveを使用しているのですが、必要なのは
①CarrierWaveのインストール
Gemfile.lockに carrierwaveの記載があったためインストールはされていると判断します。
`Gemfile.lock`
```
 carrierwave (= 2.0.2)
```
②uploaderの生成
保存先、デフォルトの画像、拡張子の指定は行なっています。
`avatar_uploader.rb`
```
class AvatarUploader < CarrierWave::Uploader::Base
  # Include RMagick or MiniMagick support:
  # include CarrierWave::RMagick
  # include CarrierWave::MiniMagick

  # Choose what kind of storage to use for this uploader:
  storage :file
  # storage :fog

  # Override the directory where uploaded files will be stored.
  # This is a sensible default for uploaders that are meant to be mounted:
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  def default_url
    'sample.png'
  end

  # Provide a default URL as a default if there hasn't been a file uploaded:
  # def default_url(*args)
  #   # For Rails 3.1+ asset pipeline compatibility:
  #   # ActionController::Base.helpers.asset_path("fallback/" + [version_name, "default.png"].compact.join('_'))
  #
  #   "/images/fallback/" + [version_name, "default.png"].compact.join('_')
  # end

  # Process files as they are uploaded:
  # process scale: [200, 300]
  #
  # def scale(width, height)
  #   # do something
  # end

  # Create different versions of your uploaded files:
  # version :thumb do
  #   process resize_to_fit: [50, 50]
  # end

  # Add a white list of extensions which are allowed to be uploaded.
  # For images you might use something like this:
  def extension_whitelist
    %w[jpg jpeg gif png]
  end

  # Override the filename of the uploaded files:
  # Avoid using model.id or version_name here, see uploader/store.rb for details.
  # def filename
  #   "something.jpg" if original_filename
  # end
end
```
③モデルの関連付け

`user.rb`
```
mount_uploader :avatar, AvatarUploader
```
この記載により、アップローダークラスとカラムを紐付けられると思うのですが、他に必要な設定はあったでしょうか？

**Comment by kenchasonakai** [comment]
みた感じ設定は大丈夫そうな気がしますね...
バリデーション周りのエラーを修正したと思うのでavatarだけ追加してみたりして何か変化がないか試してみてください
また`ArgumentError (wrong number of arguments (given 2, expected 1)):`とのことなので
user_params.countなどを実行して引数の数とかをみてみたりしてもいいかもです

**Comment by yukari-h602** [comment]
>みた感じ設定は大丈夫そうな気がしますね...

ありがとうございます
>バリデーション周りのエラーを修正したと思うのでavatarだけ追加してみたりして何か変化がないか試してみてください

ストロングパラメーターにavatarのみ追加しました。
```
Started PATCH "/profile" for ::1 at 2023-08-15 18:27:58 +0900
Processing by ProfilesController#update as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"ws@sample.com", "name"=>"yui", "hobby"=>"test!\r\n", "avatar"=>#<ActionDispatch::Http::UploadedFile:0x000000010b61f790 @tempfile=#<Tempfile:/var/folders/xm/ymnv362s0y78r9w1mft38wsm0000gn/T/RackMultipart20230815-27505-vtsyhp.jpeg>, @content_type="image/jpeg", @original_filename="IMG_1093.jpeg", @headers="Content-Disposition: form-data; name=\"user[avatar]\"; filename=\"IMG_1093.jpeg\"\r\nContent-Type: image/jpeg\r\n">, "avatar_cache"=>""}, "commit"=>"更新する"}
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/profiles_controller.rb:20:in `set_user'
Unpermitted parameter: :avatar_cache. Context: { controller: ProfilesController, action: update, request: #<ActionDispatch::Request:0x000000010b626ab8>, params: {"_method"=>"patch", "authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"ws@sample.com", "name"=>"yui", "hobby"=>"test!\r\n", "avatar"=>#<ActionDispatch::Http::UploadedFile:0x000000010b61f790 @tempfile=#<Tempfile:/var/folders/xm/ymnv362s0y78r9w1mft38wsm0000gn/T/RackMultipart20230815-27505-vtsyhp.jpeg>, @content_type="image/jpeg", @original_filename="IMG_1093.jpeg", @headers="Content-Disposition: form-data; name=\"user[avatar]\"; filename=\"IMG_1093.jpeg\"\r\nContent-Type: image/jpeg\r\n">, "avatar_cache"=>""}, "commit"=>"更新する", "controller"=>"profiles", "action"=>"update"} }
Completed 500 Internal Server Error in 10ms (ActiveRecord: 0.3ms | Allocations: 4201)


  
ArgumentError (wrong number of arguments (given 2, expected 1)):
```
エラーログは変わっていて`:avatar_cache`が許可されてないよ的なログになっていました。
>user_params.countなどを実行して引数の数とかをみてみたりしてもいいかもです

`user_params.cont`を実行しました。そしたらNoMethodErrorが発生しました。`count`が定義されていないということなのですが、どうしたらいいのでしょう...
countメソッドが使えていないということですよね？
```
>> user_params.count
NoMethodError: undefined method `count' for #<ActionController::Parameters {"email"=>"ws@sample.com", "name"=>"yui", "hobby"=>"test!\r\n", "avatar"=>#<ActionDispatch::Http::UploadedFile:0x000000010d51cd00 @tempfile=#<Tempfile:/var/folders/xm/ymnv362s0y78r9w1mft38wsm0000gn/T/RackMultipart20230815-27505-h85syf.jpeg>, @content_type="image/jpeg", @original_filename="IMG_1093.jpeg", @headers="Content-Disposition: form-data; name=\"user[avatar]\"; filename=\"IMG_1093.jpeg\"\r\nContent-Type: image/jpeg\r\n">, "avatar_cache"=>""} permitted: true>
	from /Users/hirashimayukari/workspace/runteq/oshi-katsu/app/controllers/profiles_controller.rb:9:in `update'
```

**Comment by kenchasonakai** [comment]
> また@userではavatar: nilになってしまっているのに対し、user_paramsではアバターの情報を得られているのが原因なのでしょうか？

それはあまり関係ないような気もしますね...

手元で見てみるのでドラフトでプルリクエストを作成していただいても良いでしょうか？
https://qiita.com/tatane616/items/13da1b6797a7b871ad58

**Comment by yukari-h602** [comment]
ドラフトにてプルリクエストを作成しました。
確認をお願いいたします。

https://github.com/yukari-h602/oshi-katsu/pull/21

**Comment by kenchasonakai** [comment]
GemfileのCarrierWaveのバージョン指定が良くなかったようです
公式ドキュメントには`gem 'carrierwave', '~> 3.0'`と記載するように書いてあると思うので合わせて実装してみてください
https://github.com/carrierwaveuploader/carrierwave#installation

[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/270fda4437ad08a095d94d53dda1c1d6.png)](https://startup-technology.gyazo.com/270fda4437ad08a095d94d53dda1c1d6)

**Comment by yukari-h602** [comment]
バージョンを指定し直したら実装できました。
ありがとうございました
