### ISSUE TITLE
タグによる絞り込みをしたい

### ISSUE THREAD

**Issue by yukari-h602** [yukari-h602/oshi-katsu#22]
- 質問内容・実現したいこと
タグをクリックして投稿を絞り込み表示したいです。
- 現状発生している問題・エラーメッセージ
投稿にタグをつけることはできたのですが、タグをクリックしてもうまく絞り込みができずに全ての記事が表示されてしまいます。
タグをクリックした際のURLは`http://localhost:3000/boards?tag_name=アニメ`となっております。
- どの処理までうまく動いているのか
タグをつける、タグを編集することはできています。
- 該当のソースコード
`board_tag.rb`
```
class BoardTag < ApplicationRecord
  belongs_to :board
  belongs_to :tag

  validates :tag_id, uniqueness: { scope: :board_id }
end
```
`tag.rb`
```
class Tag < ApplicationRecord
  has_many :board_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :boards, through: :board_tags

  validates :name, uniqueness: true, presence: true
end
```
`board.rb`
```
class Board < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :board_tags, dependent: :destroy
  has_many :tags, through: :board_tags

  validates :name, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 255 }
  validates :world, presence: true, length: { maximum: 65_535 }
  validates :charm, presence: true, length: { maximum: 65_535 }
  validates :body, presence: true, length: { maximum: 65_535 }

  scope :with_tag, ->(tag_name) { joins(:tags).where(tags: { name: tag_name }) }

  def self.ransackable_attributes(auth_object = nil)
    %w[name title world charm body]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[comments user]
  end

  def save_tags(tag_names:)
    ActiveRecord::Base.transaction do
      self.tags = tag_names.map { |name| Tag.find_or_initialize_by(name: name.strip) }
      save!
    end
    true
  rescue StandardError
    false
  end

  def tag_names
    tags.map(&:name).join(',')
  end
end
```
`boards_controller.rb`
```
class BoardsController < ApplicationController
  skip_before_action :require_login, only: %i[index]
  before_action :set_board, only: %i[edit update destroy]

	def index
    boards = if(tag_name = params[:tag_name])
      Board.with_tag(tag_name)
    else
      Board.all
    end
    @q = Board.ransack(params[:q])
		@boards = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page]).per(6)
	end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      @board.save_tags(tag_names: params.dig(:board, :tag_names).try(:split, ","))
      redirect_to boards_path, success: t('defaults.message.created', item: Board.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_created', item: Board.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @board = Board.find(params[:id])
    @comment = Comment.new
    @comments = @board.comments.includes(:user).order(created_at: :desc)
  end

  def edit; end

  def update
    if @board.update(board_params)
      @board.save_tags(tag_names: params.dig(:board, :tag_names).try(:split, ","))
      redirect_to @board, success: t('defaults.message.updated', item: Board.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: Board.model_name.human)
      render :edit
    end
  end

  def destroy
    @board.destroy!

    redirect_to boards_path, success: t('defaults.message.deleted', item: Board.model_name.human)
  end

  def bookmarks
    @q = current_user.bookmark_boards.ransack(params[:q])
    @bookmark_boards = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page]).per(6)
  end

  private

  def set_board
    @board = current_user.boards.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:name, :title, :world, :charm, :body)
  end
end
```
タグはパーシャルで呼び出しています。
`tags/_tag.html.erb`
```
<%= link_to tag.name, boards_path(tag_name: tag.name), class: 'badge rounded-pill bg-primary text-decoration-none text-white' %>
```
`boards/_board.html.erb`
```
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="board-id-<%= board.id %>">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title text-center">
          <%= link_to '推しのカルテ', board_path(board), class: 'text-danger' %>
        </h4>
        <div class= "card-text mx-3 text-secondary">
          <div class="box-title"><%= Board.human_attribute_name(:name) %></div>
          <div class="box-text"><%= board.name %></div>
          <div class="box-title"><%= Board.human_attribute_name(:title) %></div>
          <div class="box-text"><%= board.title %></div>
          <div class="box-title"><%= Board.human_attribute_name(:world) %></div>
          <div class="box-text"><%= simple_format(board.world, {}, wrapper_tag: "div") %></div>
          <div class="box-title"><%= Board.human_attribute_name(:charm) %></div>
          <div class="box-text"><%= simple_format(board.charm, {}, wrapper_tag: "div") %></div>
          <div class="box-title"><%= Board.human_attribute_name(:body) %></div>
          <div class="box-text"><%= simple_format(board.body, {}, wrapper_tag: "div") %></div>
          <div class="pt-2">
            <%= render board.tags %>
          </div>
        </div>
			(略)
```
`boards/show.html.erb`
```
<div class="wrapper">
  <div class="container py-5">
    <div class="row mb-3">
      <div class="col-md-8 offset-lg-1 pb-5 mb-lg-2 pt-md-5 mt-n3 mt-md-0">
        <h1><%= t('.title') %></h1>
        <!-- 推しのカルテ内容 -->
        <article class="card">
          <div class="card-body">
            <h3 class="text-center"><%= Board.model_name.human %></h3>
            <%= render 'crud_menus', board: @board if current_user.own?(@board) %>
            <div class= "card-text mx-3 text-secondary">
              <div class="box-title"><%= Board.human_attribute_name(:name) %></div>
              <div class="box-text"><%= @board.name %></div>
              <div class="box-title"><%= Board.human_attribute_name(:title) %></div>
              <div class="box-text"><%= @board.title %></div>
              <div class="box-title"><%= Board.human_attribute_name(:world) %></div>
              <div class="box-text"><%= simple_format(@board.world, {}, wrapper_tag: "div") %></div>
              <div class="box-title"><%= Board.human_attribute_name(:charm) %></div>
              <div class="box-text"><%= simple_format(@board.charm, {}, wrapper_tag: "div") %></div>
              <div class="box-title"><%= Board.human_attribute_name(:body) %></div>
              <div class="box-text"><%= simple_format(@board.body, {}, wrapper_tag: "div") %></div>
              <div class="pt-2">
                <%= render @board.tags %>
              </div>
         (略)
```
`boards/_form.html.erb`
```
         (略)
  <div class="form-group py-2">
    <%= f.label :tag_names %>
    <%= f.text_field :tag_names, class: 'form-control', placeholder: ',で区切って入力してください' %>
  </div>
         (略)
```
- エラーから考えられる原因
`boards_controller`で`index`アクションの
```
    boards = if(tag_name = params[:tag_name])
      Board.with_tag(tag_name)
    else
      Board.all
    end
```
でうまく探せていない
- 試したこと
タグのリンクの引数を`boards_path(tag_name: tag.name)`から`boards_path(tag_name: tag)`に変更し、URLがどう変わるのか試しました。
この場合、生成されたURLは`http://localhost:3000/boards?tag_name=3`のようになったのでタグの名前で検索をしようとはしている。

以下掲示板の編集画面からタグを編集し終え、タグをクリックした際のログ
```
Started PATCH "/boards/9" for ::1 at 2023-08-27 16:03:45 +0900
Processing by BoardsController#update as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "board"=>{"name"=>"test_name", "title"=>"test", "world"=>"test", "charm"=>"test", "body"=>"test", "tag_names"=>"アニメ,擬人化"}, "commit"=>"布教する", "id"=>"9"}
  User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  Board Load (0.2ms)  SELECT "boards".* FROM "boards" WHERE "boards"."user_id" = ? AND "boards"."id" = ? LIMIT ?  [["user_id", 2], ["id", 9], ["LIMIT", 1]]
  ↳ app/controllers/boards_controller.rb:62:in `set_board'
Unpermitted parameter: :tag_names. Context: { controller: BoardsController, action: update, request: #<ActionDispatch::Request:0x0000000104f3c0c8>, params: {"_method"=>"patch", "authenticity_token"=>"[FILTERED]", "board"=>{"name"=>"test_name", "title"=>"test", "world"=>"test", "charm"=>"test", "body"=>"test", "tag_names"=>"アニメ,擬人化"}, "commit"=>"布教する", "controller"=>"boards", "action"=>"update", "id"=>"9"} }
  TRANSACTION (0.2ms)  begin transaction
  ↳ app/models/board.rb:25:in `block (2 levels) in save_tags'
  Tag Load (0.2ms)  SELECT "tags".* FROM "tags" WHERE "tags"."name" = ? LIMIT ?  [["name", "アニメ"], ["LIMIT", 1]]
  ↳ app/models/board.rb:25:in `block (2 levels) in save_tags'
  Tag Load (0.1ms)  SELECT "tags".* FROM "tags" WHERE "tags"."name" = ? LIMIT ?  [["name", "擬人化"], ["LIMIT", 1]]
  ↳ app/models/board.rb:25:in `block (2 levels) in save_tags'
  Tag Load (0.1ms)  SELECT "tags".* FROM "tags" INNER JOIN "board_tags" ON "tags"."id" = "board_tags"."tag_id" WHERE "board_tags"."board_id" = ?  [["board_id", 9]]
  ↳ app/models/board.rb:25:in `block in save_tags'
  BoardTag Delete All (0.7ms)  DELETE FROM "board_tags" WHERE "board_tags"."board_id" = ? AND "board_tags"."tag_id" IN (?, ?)  [["board_id", 9], ["tag_id", 2], ["tag_id", 4]]
  ↳ app/models/board.rb:25:in `block in save_tags'
  Tag Exists? (0.7ms)  SELECT 1 AS one FROM "tags" WHERE "tags"."name" = ? LIMIT ?  [["name", "擬人化"], ["LIMIT", 1]]
  ↳ app/models/board.rb:25:in `block in save_tags'
  Tag Create (0.3ms)  INSERT INTO "tags" ("name", "created_at", "updated_at") VALUES (?, ?, ?)  [["name", "擬人化"], ["created_at", "2023-08-27 16:03:45.120559"], ["updated_at", "2023-08-27 16:03:45.120559"]]
  ↳ app/models/board.rb:25:in `block in save_tags'
  BoardTag Exists? (0.1ms)  SELECT 1 AS one FROM "board_tags" WHERE "board_tags"."tag_id" = ? AND "board_tags"."board_id" = ? LIMIT ?  [["tag_id", 5], ["board_id", 9], ["LIMIT", 1]]
  ↳ app/models/board.rb:25:in `block in save_tags'
  BoardTag Create (0.1ms)  INSERT INTO "board_tags" ("board_id", "tag_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["board_id", 9], ["tag_id", 5], ["created_at", "2023-08-27 16:03:45.126364"], ["updated_at", "2023-08-27 16:03:45.126364"]]
  ↳ app/models/board.rb:25:in `block in save_tags'
  TRANSACTION (0.9ms)  commit transaction
  ↳ app/models/board.rb:24:in `save_tags'
Redirected to http://localhost:3000/boards/9
Completed 302 Found in 64ms (ActiveRecord: 4.2ms | Allocations: 10521)


Started GET "/boards/9" for ::1 at 2023-08-27 16:03:45 +0900
Processing by BoardsController#show as TURBO_STREAM
  Parameters: {"id"=>"9"}
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  Board Load (0.1ms)  SELECT "boards".* FROM "boards" WHERE "boards"."id" = ? LIMIT ?  [["id", 9], ["LIMIT", 1]]
  ↳ app/controllers/boards_controller.rb:31:in `show'
  Rendering layout layouts/application.html.erb
  Rendering boards/show.html.erb within layouts/application
  Rendered boards/_crud_menus.html.erb (Duration: 4.3ms | Allocations: 160)
  Tag Load (0.3ms)  SELECT "tags".* FROM "tags" INNER JOIN "board_tags" ON "tags"."id" = "board_tags"."tag_id" WHERE "board_tags"."board_id" = ?  [["board_id", 9]]
  ↳ app/views/boards/show.html.erb:23
  Rendered collection of tags/_tag.html.erb [2 times] (Duration: 0.7ms | Allocations: 253)
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  ↳ app/views/boards/show.html.erb:33
  Rendered shared/_error_messages.html.erb (Duration: 0.1ms | Allocations: 13)
  Rendered comments/_form.html.erb (Duration: 3.1ms | Allocations: 878)
  Comment Load (0.1ms)  SELECT "comments".* FROM "comments" WHERE "comments"."board_id" = ? ORDER BY "comments"."created_at" DESC  [["board_id", 9]]
  ↳ app/views/comments/_comments.html.erb:5
  Rendered collection of templates [0 times] (Duration: 0.0ms | Allocations: 13)
  Rendered comments/_comments.html.erb (Duration: 2.2ms | Allocations: 805)
  Rendered boards/show.html.erb within layouts/application (Duration: 40.5ms | Allocations: 5441)
  Rendered shared/_header.html.erb (Duration: 2.3ms | Allocations: 865)
  Rendered shared/_flash_message.html.erb (Duration: 0.1ms | Allocations: 25)
  Rendered shared/_footer.html.erb (Duration: 0.2ms | Allocations: 117)
  Rendered layout layouts/application.html.erb (Duration: 66.3ms | Allocations: 16107)
Completed 200 OK in 72ms (Views: 66.5ms | ActiveRecord: 0.7ms | Allocations: 18243)


Started GET "/boards?tag_name=%E6%93%AC%E4%BA%BA%E5%8C%96" for ::1 at 2023-08-27 16:03:51 +0900
Processing by BoardsController#index as HTML
  Parameters: {"tag_name"=>"擬人化"}
  Rendering layout layouts/application.html.erb
  Rendering boards/index.html.erb within layouts/application
  Rendered boards/_search_form.html.erb (Duration: 2.3ms | Allocations: 697)
  Board Load (0.3ms)  SELECT DISTINCT "boards".* FROM "boards" ORDER BY "boards"."created_at" DESC LIMIT ? OFFSET ?  [["LIMIT", 6], ["OFFSET", 0]]
  ↳ app/views/boards/index.html.erb:20
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" IN (?, ?)  [["id", 2], ["id", 1]]
  ↳ app/views/boards/index.html.erb:20
  Tag Load (0.1ms)  SELECT "tags".* FROM "tags" INNER JOIN "board_tags" ON "tags"."id" = "board_tags"."tag_id" WHERE "board_tags"."board_id" = ?  [["board_id", 9]]
  ↳ app/views/boards/_board.html.erb:20
  Rendered collection of tags/_tag.html.erb [2 times] (Duration: 0.8ms | Allocations: 253)
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  ↳ app/views/boards/_board.html.erb:26
  Rendered boards/_crud_menus.html.erb (Duration: 0.4ms | Allocations: 143)
  Tag Load (0.1ms)  SELECT "tags".* FROM "tags" INNER JOIN "board_tags" ON "tags"."id" = "board_tags"."tag_id" WHERE "board_tags"."board_id" = ?  [["board_id", 8]]
  ↳ app/views/boards/_board.html.erb:20
  Rendered collection of templates [0 times] (Duration: 0.0ms | Allocations: 13)
  Board Exists? (0.1ms)  SELECT 1 AS one FROM "boards" INNER JOIN "bookmarks" ON "boards"."id" = "bookmarks"."board_id" WHERE "bookmarks"."user_id" = ? AND "boards"."id" = ? LIMIT ?  [["user_id", 2], ["id", 8], ["LIMIT", 1]]
  ↳ app/models/user.rb:35:in `bookmark?'
  Bookmark Load (0.1ms)  SELECT "bookmarks".* FROM "bookmarks" WHERE "bookmarks"."user_id" = ? AND "bookmarks"."board_id" = ? LIMIT ?  [["user_id", 2], ["board_id", 8], ["LIMIT", 1]]
  ↳ app/views/boards/_unbookmark.html.erb:1
  Rendered boards/_unbookmark.html.erb (Duration: 2.5ms | Allocations: 848)
  Rendered boards/_bookmark_button.html.erb (Duration: 5.2ms | Allocations: 1819)
  Tag Load (0.1ms)  SELECT "tags".* FROM "tags" INNER JOIN "board_tags" ON "tags"."id" = "board_tags"."tag_id" WHERE "board_tags"."board_id" = ?  [["board_id", 7]]
  ↳ app/views/boards/_board.html.erb:20
  Rendered collection of templates [0 times] (Duration: 0.0ms | Allocations: 13)
  Board Exists? (0.1ms)  SELECT 1 AS one FROM "boards" INNER JOIN "bookmarks" ON "boards"."id" = "bookmarks"."board_id" WHERE "bookmarks"."user_id" = ? AND "boards"."id" = ? LIMIT ?  [["user_id", 2], ["id", 7], ["LIMIT", 1]]
  ↳ app/models/user.rb:35:in `bookmark?'
  Bookmark Load (0.1ms)  SELECT "bookmarks".* FROM "bookmarks" WHERE "bookmarks"."user_id" = ? AND "bookmarks"."board_id" = ? LIMIT ?  [["user_id", 2], ["board_id", 7], ["LIMIT", 1]]
  ↳ app/views/boards/_unbookmark.html.erb:1
  Rendered boards/_unbookmark.html.erb (Duration: 1.8ms | Allocations: 772)
  Rendered boards/_bookmark_button.html.erb (Duration: 4.2ms | Allocations: 1527)
  Tag Load (0.1ms)  SELECT "tags".* FROM "tags" INNER JOIN "board_tags" ON "tags"."id" = "board_tags"."tag_id" WHERE "board_tags"."board_id" = ?  [["board_id", 6]]
  ↳ app/views/boards/_board.html.erb:20
  Rendered collection of templates [0 times] (Duration: 0.0ms | Allocations: 13)
  Board Exists? (0.1ms)  SELECT 1 AS one FROM "boards" INNER JOIN "bookmarks" ON "boards"."id" = "bookmarks"."board_id" WHERE "bookmarks"."user_id" = ? AND "boards"."id" = ? LIMIT ?  [["user_id", 2], ["id", 6], ["LIMIT", 1]]
  ↳ app/models/user.rb:35:in `bookmark?'
  Bookmark Load (0.1ms)  SELECT "bookmarks".* FROM "bookmarks" WHERE "bookmarks"."user_id" = ? AND "bookmarks"."board_id" = ? LIMIT ?  [["user_id", 2], ["board_id", 6], ["LIMIT", 1]]
  ↳ app/views/boards/_unbookmark.html.erb:1
  Rendered boards/_unbookmark.html.erb (Duration: 1.7ms | Allocations: 772)
  Rendered boards/_bookmark_button.html.erb (Duration: 3.7ms | Allocations: 1527)
  Tag Load (0.1ms)  SELECT "tags".* FROM "tags" INNER JOIN "board_tags" ON "tags"."id" = "board_tags"."tag_id" WHERE "board_tags"."board_id" = ?  [["board_id", 5]]
  ↳ app/views/boards/_board.html.erb:20
  Rendered collection of templates [0 times] (Duration: 0.0ms | Allocations: 13)
  Board Exists? (0.1ms)  SELECT 1 AS one FROM "boards" INNER JOIN "bookmarks" ON "boards"."id" = "bookmarks"."board_id" WHERE "bookmarks"."user_id" = ? AND "boards"."id" = ? LIMIT ?  [["user_id", 2], ["id", 5], ["LIMIT", 1]]
  ↳ app/models/user.rb:35:in `bookmark?'
  Bookmark Load (0.1ms)  SELECT "bookmarks".* FROM "bookmarks" WHERE "bookmarks"."user_id" = ? AND "bookmarks"."board_id" = ? LIMIT ?  [["user_id", 2], ["board_id", 5], ["LIMIT", 1]]
  ↳ app/views/boards/_unbookmark.html.erb:1
  Rendered boards/_unbookmark.html.erb (Duration: 1.6ms | Allocations: 772)
  Rendered boards/_bookmark_button.html.erb (Duration: 3.5ms | Allocations: 1527)
  Tag Load (0.1ms)  SELECT "tags".* FROM "tags" INNER JOIN "board_tags" ON "tags"."id" = "board_tags"."tag_id" WHERE "board_tags"."board_id" = ?  [["board_id", 4]]
  ↳ app/views/boards/_board.html.erb:20
  Rendered collection of templates [0 times] (Duration: 0.0ms | Allocations: 13)
  Board Exists? (0.1ms)  SELECT 1 AS one FROM "boards" INNER JOIN "bookmarks" ON "boards"."id" = "bookmarks"."board_id" WHERE "bookmarks"."user_id" = ? AND "boards"."id" = ? LIMIT ?  [["user_id", 2], ["id", 4], ["LIMIT", 1]]
  ↳ app/models/user.rb:35:in `bookmark?'
  Bookmark Load (0.1ms)  SELECT "bookmarks".* FROM "bookmarks" WHERE "bookmarks"."user_id" = ? AND "bookmarks"."board_id" = ? LIMIT ?  [["user_id", 2], ["board_id", 4], ["LIMIT", 1]]
  ↳ app/views/boards/_unbookmark.html.erb:1
  Rendered boards/_unbookmark.html.erb (Duration: 2.0ms | Allocations: 772)
  Rendered boards/_bookmark_button.html.erb (Duration: 3.7ms | Allocations: 1527)
  Rendered collection of boards/_board.html.erb [6 times] (Duration: 51.8ms | Allocations: 20293)
  Board Count (0.1ms)  SELECT COUNT(DISTINCT "boards"."id") FROM "boards"
  ↳ app/views/boards/index.html.erb:27
  Rendered boards/index.html.erb within layouts/application (Duration: 65.8ms | Allocations: 24480)
  Rendered shared/_header.html.erb (Duration: 1.4ms | Allocations: 867)
  Rendered shared/_flash_message.html.erb (Duration: 0.0ms | Allocations: 21)
  Rendered shared/_footer.html.erb (Duration: 0.2ms | Allocations: 117)
  Rendered layout layouts/application.html.erb (Duration: 86.9ms | Allocations: 35157)
Completed 200 OK in 90ms (Views: 85.7ms | ActiveRecord: 2.1ms | Allocations: 35736)
```
お手数ではございますがご教授のほど、よろしくお願いいたします。

**Comment by tmtkzk0823** [comment]
`boards_controller.rb`
```
def index
   boards = if(tag_name = params[:tag_name])
    　　　       Board.with_tag(tag_name)
                    else
                      Board.all
                    end
    @q = Board.ransack(params[:q])
    @boards = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page]).per(6)
end

```  
こちらのコードで ローカル変数`board`に値を入れているだけになっているかもです。（その後、その値を使っていない）

**Comment by yukari-h602** [comment]
コメントありがとうございます。
```
 @q = Board.ransack(params[:q])
                      ↓変更
@q = boards.ransack(params[:q])
```
こちらに修正することで、タグ検索とキーワード検索両方できるようになりました。
タグ機能追加した際に修正し忘れていたことが原因でした。
ありがとうございました。
