### ISSUE TITLE
本番環境(Fly.io)にてS3に画像が保存できない

### ISSUE THREAD

**Issue by yukari-h602** [yukari-h602/oshi-katsu#24]
ruby "3.0.2"``Rails 7.0.6 を使用しています。
- 質問内容・実現したいこと
本番環境にてS3に画像を保存し、プロフィール画像を変更したいです。
- 現状発生している問題・エラーメッセージ
本番環境にて画像をS3に保存するため、`gem 'fog-aws'`を追加後、設定を行いました。
ローカルでは動いています。
その後本番環境にてエラーが発生し、画像を変更することができません。
`はじめのエラーコード`
```
2023-09-03T03:49:00.395 app[4d891222f4d798] nrt [info] I, [2023-09-03T03:49:00.395507 #255] INFO -- : [eb156be9-4919-457e-9d3f-65962c7d470e] Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"aph@sample.com", "name"=>"yukari", "hobby"=>"test", "avatar"=>#<ActionDispatch::Http::UploadedFile:0x00007f0524140750 @tempfile=#<Tempfile:/tmp/RackMultipart20230903-255-35uvja.jpeg>, @content_type="image/jpeg", @original_filename="IMG_1099.jpeg", @headers="Content-Disposition: form-data; name=\"user[avatar]\"; filename=\"IMG_1099.jpeg\"\r\nContent-Type: image/jpeg\r\n">, "avatar_cache"=>""}, "commit"=>"更新する"}

2023-09-03T03:49:04.685 app[4d891222f4d798] nrt [info] I, [2023-09-03T03:49:04.684928 #255] INFO -- : [eb156be9-4919-457e-9d3f-65962c7d470e] Completed 500 Internal Server Error in 4289ms (ActiveRecord: 1.5ms | Allocations: 12400)

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] F, [2023-09-03T03:49:04.685915 #255] FATAL -- : [eb156be9-4919-457e-9d3f-65962c7d470e]

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] [eb156be9-4919-457e-9d3f-65962c7d470e] Excon::Error::BadRequest (Expected(200) <=> Actual(400 Bad Request)

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] excon.error.response

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :body => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessControlListNotSupported</Code><Message>The bucket does not allow ACLs</Message><RequestId>K1YHTSSVYTF9490X</RequestId><HostId>P2VBstfbveTI7p2pYq+YRIbVePZZH9Zf5MS+xCejbO8TyzgClGkvx64v+6sBaPq/sNhbPSYQncM=</HostId></Error>"

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :cookies => [

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] ]

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :headers => {

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] "Connection" => "close"

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] "Content-Type" => "application/xml"

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] "Date" => "Sun, 03 Sep 2023 03:49:03 GMT"

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] "Server" => "AmazonS3"

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] "x-amz-id-2" => "P2VBstfbveTI7p2pYq+YRIbVePZZH9Zf5MS+xCejbO8TyzgClGkvx64v+6sBaPq/sNhbPSYQncM="

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] "x-amz-request-id" => "K1YHTSSVYTF9490X"

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] }

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :host => "oshi-katsu.s3.ap-northeast-1.amazonaws.com"

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :local_address => "172.19.148.234"

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :local_port => 44020

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :method => "PUT"

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :omit_default_port => false

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :path => "/uploads/tmp/1693712940-694848655968158-0001-2127/IMG_1099.jpeg"

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :port => 443

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :query => nil

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :reason_phrase => "Bad Request"

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :remote_ip => "52.219.199.6"

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :scheme => "https"

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :status => 400

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] :status_line => "HTTP/1.1 400 Bad Request\r\n"

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] ):

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] [eb156be9-4919-457e-9d3f-65962c7d470e]

2023-09-03T03:49:04.686 app[4d891222f4d798] nrt [info] [eb156be9-4919-457e-9d3f-65962c7d470e] app/controllers/profiles_controller.rb:9:in `update'

2023-09-03T03:54:19.620 app[4d891222f4d798] nrt [info] ERROR No such file or directory (os error 2)
```
`The bucket does not allow ACLs`となっていたので[こちら](https://take-engineer.com/the-bucket-does-not-allow-acls/)を参考にオブジェクト使用者を変更しました。
そうしたら、今度は別のエラーが発生し、やはり画像の変更をすることができません
`オブジェクト使用者変更後`
```
2023-09-03T03:58:14.868 app[3d8d9ee3c2dd58] nrt [info] I, [2023-09-03T03:58:14.868073 #255] INFO -- : [137d182b-91fc-4fba-aad4-f66ec1b2efe6] Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"aph@sample.com", "name"=>"yukari", "hobby"=>"test", "avatar"=>#<ActionDispatch::Http::UploadedFile:0x00007f1d30113f38 @tempfile=#<Tempfile:/tmp/RackMultipart20230903-255-c2psuw.jpeg>, @content_type="image/jpeg", @original_filename="IMG_1099.jpeg", @headers="Content-Disposition: form-data; name=\"user[avatar]\"; filename=\"IMG_1099.jpeg\"\r\nContent-Type: image/jpeg\r\n">, "avatar_cache"=>""}, "commit"=>"更新する"}

2023-09-03T03:58:19.086 app[3d8d9ee3c2dd58] nrt [info] I, [2023-09-03T03:58:19.086601 #255] INFO -- : [137d182b-91fc-4fba-aad4-f66ec1b2efe6] Completed 500 Internal Server Error in 4218ms (ActiveRecord: 1.8ms | Allocations: 12433)

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] F, [2023-09-03T03:58:19.087640 #255] FATAL -- : [137d182b-91fc-4fba-aad4-f66ec1b2efe6]

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] [137d182b-91fc-4fba-aad4-f66ec1b2efe6] Excon::Error::Forbidden (Expected(200) <=> Actual(403 Forbidden)

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] excon.error.response

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :body => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>AQ87SC7FD3F4SW7D</RequestId><HostId>89myVAnz7lIK6fnwqmGe/z6wfH//UFmgLG4XnRXXbZ8d0R3Jb8Yhs4S9PIarBP155xiZFtz3Blk=</HostId></Error>"

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :cookies => [

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] ]

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :headers => {

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] "Connection" => "close"

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] "Content-Type" => "application/xml"

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] "Date" => "Sun, 03 Sep 2023 03:58:18 GMT"

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] "Server" => "AmazonS3"

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] "x-amz-id-2" => "89myVAnz7lIK6fnwqmGe/z6wfH//UFmgLG4XnRXXbZ8d0R3Jb8Yhs4S9PIarBP155xiZFtz3Blk="

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] "x-amz-request-id" => "AQ87SC7FD3F4SW7D"

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] }

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :host => "oshi-katsu.s3.ap-northeast-1.amazonaws.com"

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :local_address => "172.19.150.122"

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :local_port => 36960

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :method => "PUT"

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :omit_default_port => false

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :path => "/uploads/tmp/1693713494-251645799819706-0001-8700/IMG_1099.jpeg"

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :port => 443

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :query => nil

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :reason_phrase => "Forbidden"

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :remote_ip => "52.219.136.230"

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :scheme => "https"

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :status => 403

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] :status_line => "HTTP/1.1 403 Forbidden\r\n"

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] ):

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] [137d182b-91fc-4fba-aad4-f66ec1b2efe6]

2023-09-03T03:58:19.087 app[3d8d9ee3c2dd58] nrt [info] [137d182b-91fc-4fba-aad4-f66ec1b2efe6] app/controllers/profiles_controller.rb:9:in `update'
```

- どの処理までうまく動いているのか
ローカルでは画像が変更できます。本番環境でエラーが発生します。
- 該当のソースコード
`
- エラーから考えられる原因
- 試したこと

**Comment by kenchasonakai** [comment]
まず、config/initializers/carrierwave.rbに直接アクセスキーを記載すると悪意のある人に不正に使用される恐れがあるのでやめた方が良さそうです
未対応であればcredentialsを利用すると良いと思います。

また、本番環境でぶっつけ本番でS3設定をしても修正が大変だと思うので開発環境でS3接続が出来ることを確認した後、本番環境のみS3を使うようにするのがおすすめです

**Comment by kenchasonakai** [comment]
https://pikawaka.com/rails/carrierwave
こちらの記事とご自身で設定した内容に何か差分があるか確認してみてください

**Comment by yukari-h602** [comment]
コメントありがとうございます。
アクセス許可を設定し直したら変更に成功しました。
