### ISSUE TITLE
コメントのajax機能でエラーがでる

### ISSUE THREAD

**Issue by yukari-h602** [yukari-h602/oshi-katsu#35]
ruby "3.0.2"``Rails 7.0.6 を使用しています。
- 質問内容・実現したいこと
コメントをajax化させたいです。
- 現状発生している問題・エラーメッセージ
コメント機能をajax化させたいのですが、エラーメッセージで`ActionController::UnknownFormat (ActionController::UnknownFormat):`が出ます。
```
Started POST "/boards/8/comments" for ::1 at 2023-09-24 18:25:54 +0900
Processing by CommentsController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "comment"=>{"body"=>"テスト"}, "commit"=>"コメントする", "board_id"=>"8"}
  User Load (1.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  TRANSACTION (0.1ms)  begin transaction
  ↳ app/controllers/comments_controller.rb:4:in `create'
  Board Load (0.1ms)  SELECT "boards".* FROM "boards" WHERE "boards"."id" = ? LIMIT ?  [["id", 8], ["LIMIT", 1]]
  ↳ app/controllers/comments_controller.rb:4:in `create'
  Comment Create (0.4ms)  INSERT INTO "comments" ("body", "user_id", "board_id", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?)  [["body", "テスト"], ["user_id", 1], ["board_id", 8], ["created_at", "2023-09-24 18:25:54.735396"], ["updated_at", "2023-09-24 18:25:54.735396"]]
  ↳ app/controllers/comments_controller.rb:4:in `create'
  TRANSACTION (0.6ms)  commit transaction
  ↳ app/controllers/comments_controller.rb:4:in `create'
Completed 406 Not Acceptable in 58ms (ActiveRecord: 2.8ms | Allocations: 37324)


  
ActionController::UnknownFormat (CommentsController#create is missing a template for this request format and variant.

request.formats: ["text/vnd.turbo-stream.html", "text/html"]
request.variant: []):
  
actionpack (7.0.6) lib/action_controller/metal/implicit_render.rb:42:in `default_render'
actionpack (7.0.6) lib/action_controller/metal/basic_implicit_render.rb:7:in `send_action'
actionpack (7.0.6) lib/abstract_controller/base.rb:215:in `process_action'
actionpack (7.0.6) lib/action_controller/metal/rendering.rb:165:in `process_action'
actionpack (7.0.6) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
activesupport (7.0.6) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
actiontext (7.0.6) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (7.0.6) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
activesupport (7.0.6) lib/active_support/callbacks.rb:127:in `instance_exec'
activesupport (7.0.6) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
activesupport (7.0.6) lib/active_support/callbacks.rb:138:in `run_callbacks'
actionpack (7.0.6) lib/abstract_controller/callbacks.rb:233:in `process_action'
actionpack (7.0.6) lib/action_controller/metal/rescue.rb:23:in `process_action'
actionpack (7.0.6) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
activesupport (7.0.6) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.6) lib/active_support/notifications.rb:206:in `instrument'
actionpack (7.0.6) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
actionpack (7.0.6) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
activerecord (7.0.6) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (7.0.6) lib/abstract_controller/base.rb:151:in `process'
actionview (7.0.6) lib/action_view/rendering.rb:39:in `process'
actionpack (7.0.6) lib/action_controller/metal.rb:188:in `dispatch'
actionpack (7.0.6) lib/action_controller/metal.rb:251:in `dispatch'
actionpack (7.0.6) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.0.6) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.0.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.6) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.6) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.6) lib/action_dispatch/routing/route_set.rb:852:in `call'
rack (2.2.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.7) lib/rack/etag.rb:27:in `call'
rack (2.2.7) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.7) lib/rack/head.rb:12:in `call'
actionpack (7.0.6) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
actionpack (7.0.6) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
rack (2.2.7) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.7) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.6) lib/action_dispatch/middleware/cookies.rb:704:in `call'
activerecord (7.0.6) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.6) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.6) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (7.0.6) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
actionpack (7.0.6) lib/action_dispatch/middleware/show_exceptions.rb:29:in `call'
railties (7.0.6) lib/rails/rack/logger.rb:40:in `call_app'
railties (7.0.6) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.6) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (7.0.6) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (7.0.6) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (7.0.6) lib/rails/rack/logger.rb:25:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (7.0.6) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.6) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.7) lib/rack/method_override.rb:24:in `call'
rack (2.2.7) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.6) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
actionpack (7.0.6) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
actionpack (7.0.6) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
actionpack (7.0.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.6) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.7) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.6) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
railties (7.0.6) lib/rails/engine.rb:530:in `call'
puma (5.6.6) lib/puma/configuration.rb:252:in `call'
puma (5.6.6) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.6) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.6) lib/puma/request.rb:76:in `handle_request'
puma (5.6.6) lib/puma/server.rb:443:in `process_client'
puma (5.6.6) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/boards/8" for ::1 at 2023-09-24 18:25:54 +0900
Processing by BoardsController#show as HTML
  Parameters: {"id"=>"8"}
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Board Load (0.1ms)  SELECT "boards".* FROM "boards" WHERE "boards"."id" = ? LIMIT ?  [["id", 8], ["LIMIT", 1]]
  ↳ app/controllers/boards_controller.rb:31:in `show'
  Rendering layout layouts/application.html.erb
  Rendering boards/show.html.erb within layouts/application
  Rendered boards/_crud_menus.html.erb (Duration: 0.5ms | Allocations: 238)
  Tag Load (0.4ms)  SELECT "tags".* FROM "tags" INNER JOIN "board_tags" ON "tags"."id" = "board_tags"."tag_id" WHERE "board_tags"."board_id" = ?  [["board_id", 8]]
  ↳ app/views/boards/show.html.erb:23
  Rendered collection of templates [0 times] (Duration: 0.0ms | Allocations: 19)
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/views/boards/show.html.erb:33
  Rendered comments/_form.html.erb (Duration: 1.2ms | Allocations: 739)
  Comment Load (0.1ms)  SELECT "comments".* FROM "comments" WHERE "comments"."board_id" = ? ORDER BY "comments"."created_at" DESC  [["board_id", 8]]
  ↳ app/views/comments/_comments.html.erb:5
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ?  [["id", 1]]
  ↳ app/views/comments/_comments.html.erb:5
  Rendered collection of comments/_comment.html.erb [4 times] (Duration: 3.2ms | Allocations: 1810)
  Rendered comments/_comments.html.erb (Duration: 7.5ms | Allocations: 3780)
  Rendered boards/show.html.erb within layouts/application (Duration: 29.1ms | Allocations: 17903)
  Rendered shared/_header.html.erb (Duration: 1.5ms | Allocations: 776)
  Rendered shared/_flash_message.html.erb (Duration: 0.1ms | Allocations: 29)
  Rendered shared/_footer.html.erb (Duration: 0.2ms | Allocations: 125)
  Rendered layout layouts/application.html.erb (Duration: 70.0ms | Allocations: 40317)
Completed 200 OK in 78ms (Views: 71.1ms | ActiveRecord: 0.8ms | Allocations: 44125)
```
- どの処理までうまく動いているのか
コメントは表示され、削除も機能しますが、エラーメッセージが出ます。
- 該当のソースコード
`comments/_comment.html.erb`
```
<tr id="comment-<%= comment.id %>">
  <td style="width: 60px">
    <%= image_tag comment.user.avatar_url, class: 'rounded-circle', size: '50x50' %>
  </td>
  <td>
    <h3 class="small"><%= comment.user.name %></h3>
    <div id="js-comment-<%= comment.id %>">
      <%= simple_format(comment.body) %>
    </div>
    <div id="js-textarea-comment-box-<%= comment.id %>" style="display: none;">
      <textarea id="js-textarea-comment-<%= comment.id %>" class="form-control mb-1"><%= comment.body %></textarea>
      <button class="btn btn-light js-button-edit-comment-cancel" data-comment-id="<%= comment.id %>">キャンセル</button>
      <button class="btn btn-success js-button-comment-update" data-comment-id="<%= comment.id %>">更新</button>
    </div>
  </td>
  <% if current_user.own?(comment) %>
    <td class="action">
      <ul class="list-inline justify-content-center" style="float: right;">
        <li class="list-inline-item">
          <%= link_to comment_path(comment), class: "js-delete-comment-button", data: { turbo_method: :delete, turbo_confirm: t('defaults.message.delete_confirm')}, remote: true do %>
            <i class="fas fa-trash" style="color:#BBDED6;"></i>
          <% end %>
        </li>
      </ul>
    </td>
  <% end %>
</tr>
```
`comments/_form.html.erb`
```
<div class="row mb-3">
  <div class="pt-3">
    <%= form_with model: comment, url: [board, comment], id: 'new_comment', local: false do |f| %>
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control mb-3', id: 'js-new-comment-body', row: 4, placeholder: Comment.human_attribute_name(:body) %>
      <%= f.submit t('defaults.post'), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>
```
`routes.rb(一部)`
```
	resources :boards do
		resources :comments, only: %i[create destroy], shallow: true
		collection do
			get :bookmarks
			get :autocomplete
		end
	end
```
`comments_controller.rb`
```
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    @comment.save
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end
	private
	
	def comment_params
		params.require(:comment).permit(:body).merge(board_id: params[:board_id])
	end
end
```
- エラーから考えられる原因
JS形式で受け取れていない
- 試したこと
1. [似たようなエラーの記事](https://qiita.com/mm36/items/89b0311e045e16ca612d)はあったのですが、
入力フォームに`data-remote="true"`は付いていたので状況は違うようです。
<img width="606" alt="スクリーンショット 2023-09-24 18 36 06" src="https://github.com/yukari-h602/oshi-katsu/assets/117580975/4375abfa-3fcf-4c0f-884b-5693f53dfb5b">

2.  `respond_to`でjsを受け取るように指定をした
`comments_controller.rb`
```
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
		respond_to do |format|
      @comment.save
				format.js
		end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
		respond_to do |format|
      @comment.destroy!
			format.js
		end
  end
	private
	
	def comment_params
		params.require(:comment).permit(:body).merge(board_id: params[:board_id])
	end
end
```
`エラーログ`
```
Started POST "/boards/8/comments" for ::1 at 2023-09-24 18:19:45 +0900
Processing by CommentsController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "comment"=>{"body"=>"test"}, "commit"=>"コメントする", "board_id"=>"8"}
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  TRANSACTION (0.1ms)  begin transaction
  ↳ app/controllers/comments_controller.rb:5:in `block in create'
  Board Load (0.2ms)  SELECT "boards".* FROM "boards" WHERE "boards"."id" = ? LIMIT ?  [["id", 8], ["LIMIT", 1]]
  ↳ app/controllers/comments_controller.rb:5:in `block in create'
  Comment Create (0.4ms)  INSERT INTO "comments" ("body", "user_id", "board_id", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?)  [["body", "test"], ["user_id", 1], ["board_id", 8], ["created_at", "2023-09-24 18:19:45.430305"], ["updated_at", "2023-09-24 18:19:45.430305"]]
  ↳ app/controllers/comments_controller.rb:5:in `block in create'
  TRANSACTION (0.7ms)  commit transaction
  ↳ app/controllers/comments_controller.rb:5:in `block in create'
Completed 406 Not Acceptable in 19ms (ActiveRecord: 1.5ms | Allocations: 6113)


  
ActionController::UnknownFormat (ActionController::UnknownFormat):
  
app/controllers/comments_controller.rb:4:in `create'
Started GET "/boards/8" for ::1 at 2023-09-24 18:19:45 +0900
Processing by BoardsController#show as HTML
  Parameters: {"id"=>"8"}
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Board Load (0.1ms)  SELECT "boards".* FROM "boards" WHERE "boards"."id" = ? LIMIT ?  [["id", 8], ["LIMIT", 1]]
  ↳ app/controllers/boards_controller.rb:31:in `show'
  Rendering layout layouts/application.html.erb
  Rendering boards/show.html.erb within layouts/application
  Rendered boards/_crud_menus.html.erb (Duration: 0.4ms | Allocations: 177)
  Tag Load (0.1ms)  SELECT "tags".* FROM "tags" INNER JOIN "board_tags" ON "tags"."id" = "board_tags"."tag_id" WHERE "board_tags"."board_id" = ?  [["board_id", 8]]
  ↳ app/views/boards/show.html.erb:23
  Rendered collection of templates [0 times] (Duration: 0.0ms | Allocations: 17)
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/views/boards/show.html.erb:33
  Rendered comments/_form.html.erb (Duration: 1.4ms | Allocations: 621)
  Comment Load (0.1ms)  SELECT "comments".* FROM "comments" WHERE "comments"."board_id" = ? ORDER BY "comments"."created_at" DESC  [["board_id", 8]]
  ↳ app/views/comments/_comments.html.erb:5
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ?  [["id", 1]]
  ↳ app/views/comments/_comments.html.erb:5
  Rendered collection of comments/_comment.html.erb [3 times] (Duration: 3.3ms | Allocations: 1356)
  Rendered comments/_comments.html.erb (Duration: 6.7ms | Allocations: 2921)
  Rendered boards/show.html.erb within layouts/application (Duration: 14.3ms | Allocations: 6411)
  Rendered shared/_header.html.erb (Duration: 1.6ms | Allocations: 752)
  Rendered shared/_flash_message.html.erb (Duration: 0.1ms | Allocations: 27)
  Rendered shared/_footer.html.erb (Duration: 0.2ms | Allocations: 117)
  Rendered layout layouts/application.html.erb (Duration: 36.5ms | Allocations: 17154)
Completed 200 OK in 42ms (Views: 36.8ms | ActiveRecord: 0.5ms | Allocations: 19194)
```
コメントはできたが`ActionController::UnknownFormat (ActionController::UnknownFormat):`のエラーは発生したままだが、
```
request.formats: ["text/vnd.turbo-stream.html", "text/html"]
request.variant: []):
```
から始まるエラー文は出なかった。

3. `format.html`を指定していないからと考え
[こちらのサイト](https://zenn.dev/redheadchloe/articles/e696e5680ca4dc)を参考に`format.html`を追加
`comments_controller.rb`
```
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
		respond_to do |format|
      if@comment.save
				format.html {redirect_to board_path(comment.board), flash: {success: t('defaults.message.created', item: Comment.model_name.human)}}
				format.js
			else
				format.html {redirect_to board_path(comment.board), flash: {danger: t('defaults.message.not_created', item: Comment.model_name.human)}}
				format.js
			end
		end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
		respond_to do |format|
      @comment.destroy!
			format.html {redirect_to board_path(@board), flash: {success: t('defaults.message.deleted', item: Comment.model_name.human)}}
			format.js
		end
  end
	private
	
	def comment_params
		params.require(:comment).permit(:body).merge(board_id: params[:board_id])
	end
end
```
この場合のエラーログ↓
```
Started POST "/boards/8/comments" for ::1 at 2023-09-24 18:06:44 +0900
Processing by CommentsController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "comment"=>{"body"=>"test"}, "commit"=>"コメントする", "board_id"=>"8"}
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  TRANSACTION (0.1ms)  begin transaction
  ↳ app/controllers/comments_controller.rb:5:in `block in create'
  Board Load (0.1ms)  SELECT "boards".* FROM "boards" WHERE "boards"."id" = ? LIMIT ?  [["id", 8], ["LIMIT", 1]]
  ↳ app/controllers/comments_controller.rb:5:in `block in create'
  Comment Create (0.3ms)  INSERT INTO "comments" ("body", "user_id", "board_id", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?)  [["body", "test"], ["user_id", 1], ["board_id", 8], ["created_at", "2023-09-24 18:06:45.024666"], ["updated_at", "2023-09-24 18:06:45.024666"]]
  ↳ app/controllers/comments_controller.rb:5:in `block in create'
  TRANSACTION (0.8ms)  commit transaction
  ↳ app/controllers/comments_controller.rb:5:in `block in create'
Completed 500 Internal Server Error in 82ms (ActiveRecord: 3.2ms | Allocations: 41336)


  
NameError (undefined local variable or method `comment' for #<CommentsController:0x0000000009d7b0>
Did you mean?  @comment):
  
app/controllers/comments_controller.rb:6:in `block (2 levels) in create'
app/controllers/comments_controller.rb:4:in `create'
```
`ActionController::UnknownFormat`は出なかったものの`NameError`が発生。
引数が違うとのことなのでしょうか？

お手数ではございますがご教授のほど、よろしくお願いいたします。

**Comment by kenchasonakai** [comment]
Rails7系のデフォルトでは`js.erb`は使えないと思うので非同期処理の実装はturbo_streamを使うようにしましょう
もしどうしても`js.erb`使いたい場合はrails-ujsを入れるともしかしたらできるかもしれません

**Comment by yukari-h602** [comment]
コメントありがとうございます。
[こちらのサイト](https://taopo.hatenablog.com/entry/2022/07/17/062204)ではrails7で`rails-ujs`が使用できたようでしたが、やはり
```
ActionController::UnknownFormat (CommentsController#create is missing a template for this request format and variant.

request.formats: ["text/vnd.turbo-stream.html", "text/html"]
```
は出てしまいました。
`importmap.rb`にピン留めし、
```
pin "@rails/ujs", to: "https://ga.jspm.io/npm:@rails/ujs@7.0.1/lib/assets/compiled/rails-ujs.js"
```
`application.js`に以下を追記しました。
```
import Rails from '@rails/ujs';

Rails.start();
```
これで出来ないということは`js.erb`は使用できないのでしょうか？それとも`rails-ujs`を使用する方法が違っているのでしょうか？

**Comment by kenchasonakai** [comment]
そもそものお話をすると、`rails-ujs`は非推奨になったので就活の際にきちんと説明できる特別な事情がない限りjs.erbを使用するのではなく、置き換えられているturboの機能を使って作れないのか考えると良いかと思います。
https://zenn.dev/shita1112/books/cat-hotwire-turbo/viewer/tips

どうしてもujsを使いたい場合はそもそもJSが読み込めているのか何かエラーがないかをまず探ってみてください

**Comment by yukari-h602** [comment]
なるほど...ありがとうございます。
